name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ] # Trigger on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout the source code
      - uses: actions/checkout@v3

      # 2. Set up Node.js environment
      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. Set up Bun package manager
      - uses: oven-sh/setup-bun@v1

      # 4. Install dependencies and build the project
      - run: bun install       # Use bun install for dependencies
      - run: bun run build     # This runs the build script, creating the ./dist folder

      # 4. Deploy the contents of the build folder to the gh-pages branch
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # The output folder of a Vite build
          # publish_branch: gh-pages # This is the default branch used for publishing
